### ISSUE TITLE
Fails to read tag files with encoding other than UTF-8

### ISSUE THREAD

**Issue by johnscancella** [richardrodgers/bagit#16]
https://github.com/richardrodgers/bagit/blob/master/src/main/java/edu/mit/lib/bagit/Bag.java#L412

Will fail for example when the manifest is written using UTF-16 or some other encoding. As per the bagit specification https://tools.ietf.org/html/draft-kunze-bagit-14#section-2.1.1 the encoding should be read from the bagit.txt file and used for reading the other tag files.

The Library of congress has a conformance suite that you can test your library against
https://github.com/LibraryOfCongress/bagit-conformance-suite/tree/master/v0.97/valid/UTF-16-encoded-tag-files

**Comment by richardrodgers** [comment]
Thanks for the report, johnscanella!  Also now passes the conformance suite you mention, which is a great resource for finding corner cases, etc. Be glad to address any other issues/deficiencies you find.
